<a href="https://colab.research.google.com/github/remizah/Luminar_projects/blob/main/Luminar_traindata_MLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Datasets/train-data.csv')
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [ ]:
df['Brand'] = df['Name'].apply(lambda x: x.split()[0])
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Brand
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,Maruti
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,Hyundai
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,Honda
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,Maruti
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75,Maruti
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00,Hyundai
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90,Mahindra
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65,Maruti
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50,Chevrolet

In [ ]:
df.isna().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
Brand                   0
dtype: int64

In [ ]:
df.drop(['Unnamed: 0', 'Name', 'New_Price'],axis=1, inplace=True)
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,4.75,Maruti
6015,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.00,Hyundai
6016,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,2.90,Mahindra
6017,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,2.65,Maruti
6018,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,2.50,Chevrolet

In [ ]:
df.dtypes

Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
Price                float64
Brand                 object
dtype: object

In [ ]:
#mode
df['Seats']=df['Seats'].fillna(df['Seats'].mode()[0])

In [ ]:
df.isna().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                 0
Price                 0
Brand                 0
dtype: int64

In [ ]:
df['Mileage']=df['Mileage'].str.replace('km/kg','')
df['Mileage']=df['Mileage'].str.replace('kmpl','')
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Mumbai,2010,72000,CNG,Manual,First,26.6,998 CC,58.16 bhp,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582 CC,126.2 bhp,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.2,1199 CC,88.7 bhp,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248 CC,88.76 bhp,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968 CC,140.8 bhp,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Delhi,2014,27365,Diesel,Manual,First,28.4,1248 CC,74 bhp,5.0,4.75,Maruti
6015,Jaipur,2015,100000,Diesel,Manual,First,24.4,1120 CC,71 bhp,5.0,4.00,Hyundai
6016,Jaipur,2012,55000,Diesel,Manual,Second,14.0,2498 CC,112 bhp,8.0,2.90,Mahindra
6017,Kolkata,2013,46000,Petrol,Manual,First,18.9,998 CC,67.1 bhp,5.0,2.65,Maruti
6018,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936 CC,57.6 bhp,5.0,2.50,Chevrolet

In [ ]:
df['Power']=df['Power'].str.replace('bhp','')
df
# df['Power']=df['Power'].str.replace('null ','0')

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Mumbai,2010,72000,CNG,Manual,First,26.6,998 CC,58.16,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582 CC,126.2,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.2,1199 CC,88.7,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248 CC,88.76,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968 CC,140.8,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Delhi,2014,27365,Diesel,Manual,First,28.4,1248 CC,74,5.0,4.75,Maruti
6015,Jaipur,2015,100000,Diesel,Manual,First,24.4,1120 CC,71,5.0,4.00,Hyundai
6016,Jaipur,2012,55000,Diesel,Manual,Second,14.0,2498 CC,112,8.0,2.90,Mahindra
6017,Kolkata,2013,46000,Petrol,Manual,First,18.9,998 CC,67.1,5.0,2.65,Maruti
6018,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936 CC,57.6,5.0,2.50,Chevrolet

In [ ]:
df['Engine']=df['Engine'].str.replace('CC','')
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,Mumbai,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0,1.75,Maruti
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,12.50,Hyundai
2,Chennai,2011,46000,Petrol,Manual,First,18.2,1199,88.7,5.0,4.50,Honda
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00,Maruti
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,17.74,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Delhi,2014,27365,Diesel,Manual,First,28.4,1248,74,5.0,4.75,Maruti
6015,Jaipur,2015,100000,Diesel,Manual,First,24.4,1120,71,5.0,4.00,Hyundai
6016,Jaipur,2012,55000,Diesel,Manual,Second,14.0,2498,112,8.0,2.90,Mahindra
6017,Kolkata,2013,46000,Petrol,Manual,First,18.9,998,67.1,5.0,2.65,Maruti
6018,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.6,5.0,2.50,Chevrolet

In [ ]:
df.dtypes

Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
Price                float64
Brand                 object
dtype: object

In [ ]:
df['Mileage']=df['Mileage'].astype(float)
df.dtypes

Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage              float64
Engine                object
Power                 object
Seats                float64
Price                float64
Brand                 object
dtype: object

In [ ]:
df.loc[df['Power']=='null']

Empty DataFrame
Columns: [Location, Year, Kilometers_Driven, Fuel_Type, Transmission, Owner_Type, Mileage, Engine, Power, Seats, Price, Brand]
Index: []

In [ ]:
df['Power']=df['Power'].str.replace('null',"0")

In [ ]:
df['Power']=df['Power'].astype(float)

In [ ]:
df.dtypes

Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage              float64
Engine                object
Power                float64
Seats                float64
Price                float64
Brand                 object
dtype: object

In [ ]:
df['Mileage']=df['Mileage'].fillna(df['Mileage'].mean())
df['Engine']=df['Engine'].fillna(df['Engine'].mode()[0])

In [ ]:
df.isna().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine                0
Power                36
Seats                 0
Price                 0
Brand                 0
dtype: int64

In [ ]:
import numpy as np
df['Power']=df['Power'].replace(0,np.NaN)

In [ ]:
df.isna().sum()

Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                0
Engine                 0
Power                143
Seats                  0
Price                  0
Brand                  0
dtype: int64

In [ ]:
df.Power

0        58.16
1       126.20
2        88.70
3        88.76
4       140.80
         ...
6014     74.00
6015     71.00
6016    112.00
6017     67.10
6018     57.60
Name: Power, Length: 6019, dtype: float64

In [ ]:
mdn=df['Power'].median()
mdn

97.7

In [ ]:
df['Power']=df['Power'].fillna(df['Power'].mode()[0])

In [ ]:
df.isna().sum()

Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
Brand                0
dtype: int64

In [ ]:
df.dtypes

Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage              float64
Engine                object
Power                float64
Seats                float64
Price                float64
Brand                 object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['Location']=encoder.fit_transform(df['Location'])
df['Fuel_Type']=encoder.fit_transform(df['Fuel_Type'])
df['Transmission']=encoder.fit_transform(df['Transmission'])
df['Owner_Type']=encoder.fit_transform(df['Owner_Type'])
df['Brand']=encoder.fit_transform(df['Brand'])

In [ ]:
df.dtypes

Location               int64
Year                   int64
Kilometers_Driven      int64
Fuel_Type              int64
Transmission           int64
Owner_Type             int64
Mileage              float64
Engine                object
Power                float64
Seats                float64
Price                float64
Brand                  int64
dtype: object

In [ ]:
df

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Brand
0,9,2010,72000,0,1,0,26.60,998,58.16,5.0,1.75,18
1,10,2015,41000,1,1,0,19.67,1582,126.20,5.0,12.50,10
2,2,2011,46000,4,1,0,18.20,1199,88.70,5.0,4.50,9
3,2,2012,87000,1,1,0,20.77,1248,88.76,7.0,6.00,18
4,3,2013,40670,1,0,2,15.20,1968,140.80,5.0,17.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,4,2014,27365,1,1,0,28.40,1248,74.00,5.0,4.75,18
6015,6,2015,100000,1,1,0,24.40,1120,71.00,5.0,4.00,10
6016,6,2012,55000,1,1,2,14.00,2498,112.00,8.0,2.90,17
6017,8,2013,46000,4,1,0,18.90,998,67.10,5.0,2.65,18
6018,5,2011,47000,1,1,0,25.44,936,57.60,5.0,2.50,4

In [ ]:
X=df.drop(['Price'],axis=1)
X

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand
0,9,2010,72000,0,1,0,26.60,998,58.16,5.0,18
1,10,2015,41000,1,1,0,19.67,1582,126.20,5.0,10
2,2,2011,46000,4,1,0,18.20,1199,88.70,5.0,9
3,2,2012,87000,1,1,0,20.77,1248,88.76,7.0,18
4,3,2013,40670,1,0,2,15.20,1968,140.80,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...
6014,4,2014,27365,1,1,0,28.40,1248,74.00,5.0,18
6015,6,2015,100000,1,1,0,24.40,1120,71.00,5.0,10
6016,6,2012,55000,1,1,2,14.00,2498,112.00,8.0,17
6017,8,2013,46000,4,1,0,18.90,998,67.10,5.0,18
6018,5,2011,47000,1,1,0,25.44,936,57.60,5.0,4

In [ ]:
y=df.iloc[:,-2]
y

0        1.75
1       12.50
2        4.50
3        6.00
4       17.74
        ...
6014     4.75
6015     4.00
6016     2.90
6017     2.65
6018     2.50
Name: Price, Length: 6019, dtype: float64

**Using Scaler**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()
X=Scaler.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=18,test_size=0.3)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred=mlr.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print('r2 score:',r2_score(y_test,y_pred))
print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))

r2 score: 0.7251592588684272
MAE: 3.752294014972994
MSE: 33.79446587775979
RMSE: 5.81330077303418

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.7251592588684272

**Using another Regression Algorithm,**

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [ ]:
y_predknn=knn.predict(X_test)
y_predknn

array([30.99 ,  1.77 ,  5.9  , ...,  5.502,  5.08 ,  2.85 ])

In [ ]:
X_test

array([[0.4       , 0.80952381, 0.00566615, ..., 0.2919361 , 0.5       ,
        0.53333333],
       [0.        , 0.42857143, 0.01105091, ..., 0.02301255, 0.5       ,
        0.6       ],
       [0.9       , 0.76190476, 0.01067628, ..., 0.1058197 , 0.5       ,
        0.26666667],
       ...,
       [0.6       , 0.80952381, 0.00966625, ..., 0.10384176, 0.5       ,
        0.96666667],
       [0.        , 0.71428571, 0.01089706, ..., 0.07531381, 0.8       ,
        0.13333333],
       [0.5       , 0.57142857, 0.0076662 , ..., 0.08501331, 0.5       ,
        0.33333333]])

In [ ]:
print(r2_score(y_test,y_predknn))

0.7809269327585726